---
title: "Maladies cardiovasculaires (ROC)"
subtitle: "Courbes ROC"
author: '___'
date: "___"
output: html_document
---

```{r setup, include=FALSE}
SciViews::R
library(mlearning)
library(ROCR)
```


# Objectif

Ce document s'intéresse aux courbes ROC. Proposez le meilleur algorithme afin de prédire la variable `cardio` du jeu de données `cardio.rds`.

<!--% Ce projet est un projet cadré. Vous devez uniquement répondre à la question posée. Ne modifiez pas le nom des chunks. -->

# Analyses

<!--% Importez le jeu de données `cardio.rds`. Assurez vous que chaque variable soit dans un format correct. -->

```{r import}
cardio <-
```

<!--% Utilisez la fonction `table()` afin de mettre en évidence le nombre de niveau de la variable `cardio` ainsi que le nombre d'occurences par niveau de cette variable. -->

```{r table}

```


## Random Forest

<!--% Réalisez un classifieur par forêt aléatoire sur le jeu de données afin de prédire la variable `cardio`. Critiquez cet algorithme en 5 lignes maximum. -->

```{r rf}
cardio_rf <- mlRforest()
cardio_pred <- cvpredict()
cardio_conf <- confusion()
summary(cardio_conf)
```

## Courbe ROC 

<!--% Réalisez une validation croisée 10 fois en tenant compte de l'appartenance à la classe (membership). Commentez en 2 lignes le résultat. -->

```{r membership}
cardio_rf_mem <- cvpredict(___, cv.k = 10, type = "membership")
head(cardio_rf_mem)
```

<!--% Réalisez le graphique qui compare les vrais positifs et les faux positifs. Commentez ce graphique en 5 lignes maximum. -->

```{r roc_curve}
cardio_rf_predroc <- prediction(cardio_rf_mem[, 2], ___)
cardio_rf_perfroc <- performance(cardio_rf_predroc, "tpr", "fpr")
plot(cardio_rf_perfroc); abline(a = 0, b = 1, lty = 2)
```

<!--% Calculez l'aire sous la courbe (AUC). -->

```{r}
pROC::auc(___)
```

