---
title: "Maladies cardiovasculaires (rforest)"
subtitle: "Métriques et proportions"
author: '___'
date: "___"
output: html_document
---

```{r setup, include=FALSE}
SciViews::R
library(mlearning)
```

# Objectif

Ce document s'intéresse aux proportions des groupes et de l'effet sur les métriques. Proposez le meilleur algorithme afin de prédire la variable `cardio` du jeu de données `cardio.rds`. Modifiez les proportions afin d'améliorer le Recall de votre algorithme.

<!--% Ce projet est un projet cadré. Vous devez uniquement répondre à la question posée, et ne modifiez pas le nom des chunks. -->

# Analyses

<!--% Importez le jeu de données `cardio.rds`. Assurez-vous que chaque variable soit dans un format correct. --> 

```{r import}
cardio <-
```

<!--% Utilisez la fonction `table()` afin de mettre en évidence le nombre de niveau de la variable `cardio` ainsi que le nombre d'occurences par niveau de cette variable. -->

```{r table}

```

<!--%  Réalisez 3 graphiques différents de votre choix pour explorer ce jeu de données. Chaque graphique doit être commenté en 1 à 2 lignes. -->

```{r plot1}

```

```{r plot2}

```

```{r plot3}

```

## Random Forest

<!--% Réalisez un classifieur par foret aléatoire sur le jeu de données afin de prédire la variable `cardio`. Critiquez cet algorithme en 5 lignes maximum. -->

```{r rforest}
vascular_rf <- mlRforest()
vascular_pred <- cvpredict()
vascular_conf <- confusion()
summary(vascular_conf)
```

## Maximisation du Recall

<!--% Divisez votre jeu de données en deux avec les patients positif et les patients négatifs à la présence de maladie cardiovasculaire. Sélectionnez les 1500 patients positifs et 1000 patients négatifs. -->

```{r cardio_prop}
cardio_pos <- 
cardio_neg <- 
cardio_prop <- bind_rows(cardio_pos, cardio_neg)
```

<!--%  Réalisez un second classifieur par forêt aléatoire sur ce nouveau tableau qui comprend volontairement plus de patients positifs que négatifs. Commentez votre modèle en 5 lignes maximum. -->

```{r rforest2}
vascular_rf1 <- mlRforest()
vascular_pred1 <- cvpredict()
vascular_conf1 <- confusion()
summary(vascular_conf1)
```

<!--% Adaptez les résultats de la matrice de confusion en tenant compte des véritables proportions. Commentez le résultat issu de cette adaptation en 5 lignes maximum. -->

```{r prior}
cardio_prior <- table(___) / nrow(___)
cardio_prior <- structure(as.numeric(cardio_prior),
  names = names(cardio_prior))
cardio_prior
```

```{r metrics_with_prior}
prior(___) <- cardio_prior
summary(___)
```


# Conclusion 

<!--%  Comparez votre analyse avec et sans modification des proportions en 2 ou 3 paragraphes maximum. -->


