---
title: "Maladies cardiovasculaires : Comparaison de classifieurs"
author: '___'
date: "___"
output: html_document
---

```{r setup, include=FALSE}
SciViews::R
library(mlearning)
```

# Objectif

Ce carnet de notes fait suite au document `cardio_proportions.Rmd`. L'objectif est d'optimiser les paramètres de trois classifieurs.

<!--% Ce projet est un projet cadré. Vous devez uniquement répondre à la question posée. Ne modifiez pas le nom des chunks. -->

# Analyses

<!--%  Importez le jeu de données `cardio.rds`. Assurez-vous que chaque variable soit dans un format correct. -->

```{r import}
cardio <-
```

<!--# La visualisation des données a déja été réalisée dans le document `cardio_proportions.Rmd`-->

## Optimisation de classifieurs

<!--% Réalisez un set d'apprentissage et un set de test. Divisez vos données en 2. 2/3 de vos observations sont à employer dans le set d'apprentissage. -->

```{r training}

```

<!--% Pour chacune des 3 méthodes (réseaux de neurones artificiels, machine à vecteurs supports et la forêt aléatoire), entraînez un classifieur et optimisez-le en choisissant les meilleurs paramètres. Indiquez les différentes valeurs des paramètres testés, mais ne conservez que le meilleur modèle (ne dupliquez pas les chunks !) -->

### Réseau de neurones

```{r nnet}

```

```{r nnet_confusion}

```

```{r nnet_metrics}

```

<!--% Paramètres testés et critère de choix du classifieur optimal ci-dessous en 2 phrases max. -->

### Machine à vecteurs supports

```{r svm}

```

```{r svm_confusion}

```

```{r svm_metrics}

```

<!--% Paramètres testés et critère de choix du classifieur optimal ci-dessous en 2 phrases max. -->

## Random forest

```{r rforest}

```

```{r rf_plot}

```

```{r rf_confusion}

```

```{r rf_metrics}

```

<!--% Paramètres testés et critère de choix du classifieur optimal ci-dessous en 2 phrases max. -->

## Discussion et conclusion

<!--% Indiquez ci-dessous en 5 phrases maximum quel classifieur vous considérez comme le meilleur, pourquoi et sur base de quelles métriques -->
